Repository vtexdocs/helpcenter, pull requests merged in 2024-12, with the labels that each got.

#142 docs: update readme
  README.md
Labels: release-no

#132 feat: troubleshooting page search
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
  src/pages/troubleshooting/index.tsx
  src/utils/constants.ts
Labels: release-minor

#71 Add copy link button to documentation pages
  src/components/copy-link-button/index.tsx
  src/components/copy-link-button/styles.ts
  src/components/tooltip/index.tsx
  src/components/tutorial-markdown-render/index.tsx
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
  src/pages/announcements/[slug].tsx
  src/pages/docs/tracks/[slug].tsx
  src/pages/faq/[slug].tsx
  src/pages/known-issues/[slug].tsx
  src/pages/troubleshooting/[slug].tsx
  src/styles/documentation-page.ts
Labels: release-patch
