Repository vtexdocs/helpcenter, pull requests merged in 2024-10, with the labels that each got.

#97 fix: word breaking and width off tables columns
  src/styles/documentation-page.ts
  src/styles/global.css
Labels: release-patch

#111 fix: breadcrumbs rendering link instead of text
  src/components/breadcrumb/index.tsx
Labels: release-patch

#107 feat: working code block
  package.json
  src/pages/_app.tsx
  src/pages/announcements/[slug].tsx
  src/pages/docs/tracks/[slug].tsx
  src/pages/docs/tutorial/[slug].tsx
  src/pages/faq/[slug].tsx
  src/pages/known-issues/[slug].tsx
  src/styles/code-hike-theme.ts
Labels: release-minor

#77 Feat/announcement navigate to article
  src/components/announcement-section/index.tsx
  src/components/announcement-timeline-card/index.tsx
  src/components/announcement-timeline-card/styles.ts
  src/pages/index.tsx
Labels: release-minor

#81 Reverse footer order
  src/components/education-section/index.tsx
Labels: release-no

#82 Adjust pagination behavior
  src/components/pagination/index.tsx
Labels: release-patch

#110 feat/localized slugs
  package.json
  public/navigation.json
  src/components/locale-switcher-footer/index.tsx
  src/components/locale-switcher/index.tsx
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
  src/pages/announcements/[slug].tsx
  src/pages/announcements/index.tsx
  src/pages/docs/tracks/[slug].tsx
  src/pages/docs/tracks/index.tsx
  src/pages/docs/tutorial/[slug].tsx
  src/utils/enumerate-navigation.ts
  src/utils/navigation-utils.ts
Labels: release-patch

#117 fix: localized slugs build
  netlify.toml
  package.json
  src/pages/docs/tracks/[slug].tsx
  src/pages/docs/tutorial/[slug].tsx
Labels: release-patch

#114 Fixing sentence case and other minor UI text issues
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
Labels: release-no

#115 Fix/breadcrumbs links without locale
  src/components/breadcrumb/index.tsx
  src/components/breadcrumb/styles.ts
  src/pages/announcements/[slug].tsx
  src/pages/docs/tracks/[slug].tsx
  src/pages/docs/tutorial/[slug].tsx
  src/pages/faq/[slug].tsx
  src/pages/known-issues/[slug].tsx
  src/utils/getBreadcrumbsList.ts
Labels: release-patch

#76 fix: filter button height
  src/components/filter/styles.ts
Labels: release-patch

#95 Feat/faq page modules chip
  src/components/chip-filter/index.tsx
  src/components/chip-filter/styles.ts
  src/components/filter/index.tsx
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
  src/pages/faq/index.tsx
  src/pages/known-issues/index.tsx
  src/styles/filterable-cards-page.ts
  src/styles/known-issues-page.ts
Labels: release-minor

#112 fix: theme to match devportal
  src/styles/code-hike-theme.ts
Labels: release-patch

#80 Increase number of results in search pages
  src/pages/announcements/index.tsx
  src/pages/faq/index.tsx
  src/pages/known-issues/index.tsx
Labels: release-no

#78 Remove text from filter button on mobile
  src/components/filter/index.tsx
  src/components/filter/styles.ts
Labels: release-minor

#51 feat: altered icon from menu
  src/components/icons/faq-icon.tsx
  src/components/icons/warning-icon.tsx
  src/utils/constants.ts
Labels: release-minor

#118 fix(navigation): update announcements sorting
  public/navigation.json
Labels: release-no

#119 chore: remove satisfaction research announcement bar
  src/components/header/index.tsx
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
Labels: release-patch

#120 Feat/inline icons support
  package.json
  src/pages/_app.tsx
  src/styles/global.css
  yarn.lock
Labels: release-minor

#122 Fix/ki internal reference
  src/pages/known-issues/[slug].tsx
  src/pages/known-issues/index.tsx
Labels: release-patch

#129 feat: add data and privacy track
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
  src/pages/docs/tracks/index.tsx
Labels: release-no

#130 fix: support links
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
  src/utils/constants.ts
Labels: release-no
