Repository vtexdocs/helpcenter, pull requests merged in 2024-01, with the labels that each got.

#18 feat/get-docs
  netlify.toml
  package.json
  src/components/article-pagination/index.tsx
  src/components/error-boundary/index.jsx
  src/pages/500.tsx
  src/pages/_app.tsx
  src/pages/api/docs.ts
  src/pages/api/revalidate.ts
  src/pages/docs/tracks/[slug].tsx
  src/pages/docs/tutorial/[slug].tsx
  src/pages/updates/announcements/[slug].tsx
  src/utils/getDocsPaths.ts
  src/utils/getFileContributors.ts
  src/utils/octokitConfig.ts
  tsconfig.json
  yarn.lock
Labels: release-no

#23 Feat/start here
  package.json
  public/images/start-here.png
  public/navigation.json
  src/components/whats-next-card/index.tsx
  src/components/whats-next-card/styles.ts
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
  src/pages/docs/tracks/[slug].tsx
  src/pages/docs/tracks/index.tsx
  src/pages/docs/tutorial/index.tsx
  src/styles/documentation-page.ts
  src/utils/enumerate-navigation.ts
  src/utils/getNavigation.ts
  src/utils/remark_plugins/remarkReadingTime.ts
  yarn.lock
Labels: release-minor

#24 chore(package.json): update components lib version
  package.json
  src/utils/remark_plugins/remarkReadingTime.ts
  yarn.lock
Labels: release-patch

#25 Feat/sitemap
  .gitignore
  next-sitemap.config.js
  package.json
  src/pages/server-sitemap.xml/index.ts
  yarn.lock
Labels: release-no
