Repository vtexdocs/helpcenter, pull requests merged in 2024-11, with the labels that each got.

#133 fix: no fix status for ki cards
  src/components/known-issue-card/index.tsx
  src/components/tag/styles.ts
  src/pages/known-issues/index.tsx
  src/utils/constants.ts
  src/utils/typings/types.ts
Labels: release-patch

#135 style: add list spacing
  src/styles/documentation-page.ts
Labels: release-auto

#136 chore: delete unused files
  public/docs/api-guides/billing-options.md
  public/docs/api-guides/clients.md
  public/docs/api-guides/developing-an-app.md
  public/docs/api-reference/Catalog-API.json
  public/docs/api-reference/Checkout-API.json
  public/docs/api-reference/antifraud-provider-protocol-overview.json
  public/docs/api-reference/giftcard.json
  src/pages/api/disable-preview.ts
  src/pages/api/docs.ts
  src/pages/api/feedback.ts
  src/pages/api/navigation.ts
  src/pages/api/openapi/[slug].tsx
  src/pages/api/preview.ts
  src/pages/api/proxy/[url].ts
  src/pages/api/revalidate.ts
  src/styles/api-guides.ts
  src/styles/apps-page.ts
  src/styles/global.css
  src/styles/release-notes.ts
  src/utils/getReferencePaths.ts
Labels: release-no

#134 feat: new tutorial landing page version
  public/navigation.json
  src/components/see-also-section/functions.ts
  src/components/tutorial-index/index.tsx
  src/components/tutorial-markdown-render/index.tsx
  src/components/whats-next-card/tutorials/index.tsx
  src/components/whats-next-card/tutorials/styles.ts
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
  src/pages/docs/tutorial/[slug].tsx
  src/pages/docs/tutorial/index.tsx
  src/pages/editor/sidebar.tsx
  src/pages/sitemap/index.tsx
  src/utils/constants.ts
  src/utils/typings/types.ts
  src/utils/typings/unionTypes.ts
Labels: release-minor

#137 feat: hide unpublished content
  src/components/known-issue-card/index.tsx
  src/pages/announcements/[slug].tsx
  src/pages/announcements/index.tsx
  src/pages/docs/tracks/[slug].tsx
  src/pages/docs/tutorial/[slug].tsx
  src/pages/faq/[slug].tsx
  src/pages/faq/index.tsx
  src/pages/index.tsx
  src/pages/known-issues/[slug].tsx
  src/pages/known-issues/index.tsx
  src/pages/troubleshooting/[slug].tsx
  src/pages/troubleshooting/index.tsx
  src/utils/typings/types.ts
Labels: release-auto

#140 style: add textContainer to documentation pages
  src/components/tutorial-markdown-render/index.tsx
  src/pages/announcements/[slug].tsx
  src/pages/docs/tracks/[slug].tsx
  src/pages/faq/[slug].tsx
  src/pages/known-issues/[slug].tsx
  src/pages/troubleshooting/[slug].tsx
  src/pages/updates/documentation-updates/index.tsx
  src/styles/announcement-page.ts
Labels: release-patch
