Repository vtexdocs/helpcenter, pull requests merged in 2024-02, with the labels that each got.

#26 Feat/known issues
  package.json
  src/components/education-section/styles.ts
  src/components/filter/index.tsx
  src/components/filter/styles.ts
  src/components/icons/filter-icon.tsx
  src/components/icons/trashcan-icon.tsx
  src/components/known-issue-card/index.tsx
  src/components/known-issue-card/styles.ts
  src/components/layout.tsx
  src/components/pagination/index.tsx
  src/components/pagination/styles.ts
  src/components/select/index.tsx
  src/components/select/styles.ts
  src/components/support-section/styles.ts
  src/components/tag/index.tsx
  src/components/tag/styles.ts
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
  src/pages/index.tsx
  src/pages/known-issues/[slug].tsx
  src/pages/known-issues/index.tsx
  src/styles/documentation-page.ts
  src/styles/known-issues-page.ts
  src/utils/constants.ts
  src/utils/getDocsPaths.ts
  src/utils/typings/types.ts
  yarn.lock
Labels: release-minor

#31 Feat/tutorials
  public/navigation.json
  src/components/article-pagination/index.tsx
  src/components/article-pagination/styles.ts
  src/components/tutorial-index/index.tsx
  src/components/tutorial-markdown-render/index.tsx
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
  src/pages/docs/tutorial/[slug].tsx
  src/styles/documentation-page.ts
  src/utils/getNavigation.ts
  src/utils/navigation-utils.ts
Labels: release-minor

#34 fix: changes links in constants file
  src/utils/constants.ts
Labels: release-no

#35 feat(known-issues): add status translation
  src/components/known-issue-card/index.tsx
Labels: release-patch
