Repository vtexdocs/helpcenter, pull requests merged in 2025-08, with the labels that each got.

#260 fix: announcements section
  public/landing_page_announcements.json
  src/components/announcement-card/index.tsx
  src/components/announcement-section/index.tsx
  src/components/announcement-timeline-card/index.tsx
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
  src/utils/getAnnouncementsJson.ts
Labels: release-no

#263 style(icons): fix icon thickness, stroke and fill
  src/components/icons/developer-portal-icon.tsx
  src/components/icons/graph-icon.tsx
  src/components/icons/megaphone-icon.tsx
  src/components/icons/troubleshooting-icon.tsx
  src/components/icons/warning-icon.tsx
Labels: release-no, styling

#266 fix(header): fix announcement bar and header behavior
  src/components/header/index.tsx
  src/components/layout.tsx
Labels: release-no

#264 refactor(pages): separate reusable fetchBatch code
  package.json
  src/components/pagination/index.tsx
  src/pages/announcements/index.tsx
  src/pages/faq/index.tsx
  src/pages/index.tsx
  src/pages/known-issues/index.tsx
  src/pages/troubleshooting/index.tsx
  src/utils/fetchBatchGithubData.ts
  src/utils/getDocsPaths.ts
  src/utils/logging/log-util.ts
Labels: release-patch

#270 fix(search): update components package to v6.0.6
  package.json
  public/navigation.json
  src/components/layout.tsx
  src/components/tutorial-markdown-render/index.tsx
  src/pages/announcements/[slug].tsx
  src/pages/announcements/index.tsx
  src/pages/docs/tracks/[slug].tsx
  src/pages/docs/tracks/index.tsx
  src/pages/docs/tutorials/index.tsx
  src/pages/faq/[slug].tsx
  src/pages/faq/index.tsx
  src/pages/known-issues/[slug].tsx
  src/pages/search/index.tsx
  src/utils/constants.ts
  src/utils/typings/unionTypes.ts
Labels: release-patch

#274 refactor(pages): refactor pages for easier maintanability
  src/components/icons/graph-icon.tsx
  src/pages/announcements/[slug].tsx
  src/pages/docs/tracks/[slug].tsx
  src/pages/docs/tutorials/[slug].tsx
  src/pages/faq/[slug].tsx
  src/pages/known-issues/[slug].tsx
  src/pages/troubleshooting/[slug].tsx
  src/utils/extractStaticPropsParams.ts
  src/utils/fetchFileContributors.ts
  src/utils/fetchRawMarkdown.ts
Labels: release-patch

#275 fix(tutorials): fix keyPath usage
  src/pages/announcements/[slug].tsx
  src/pages/docs/tutorials/[slug].tsx
Labels: release-no

#277 feat(pages): add synopsis to announcements cards
  package.json
  src/components/announcement-card/index.tsx
  src/components/announcement-card/styles.ts
  src/pages/announcements/index.tsx
  src/pages/troubleshooting/[slug].tsx
  src/utils/typings/types.ts
Labels: release-no

#278 fix(pages): redirect to localized if keypath
  src/components/tutorial-markdown-render/index.tsx
  src/pages/announcements/[slug].tsx
  src/pages/docs/tracks/[slug].tsx
  src/pages/docs/tutorials/[slug].tsx
  src/pages/faq/[slug].tsx
  src/pages/known-issues/[slug].tsx
  src/pages/troubleshooting/[slug].tsx
Labels: release-no

#280 style(components): minor improvements
  package.json
  src/components/chip-filter/styles.ts
  src/components/documentation-section-card/styles.ts
  src/components/dropdown-menu/styles.ts
  src/components/icons/faq-icon.tsx
  src/components/support-section-card/styles.ts
  src/messages/pt.json
  src/pages/docs/tutorials/index.tsx
  src/styles/global.css
  src/utils/extractStaticPropsParams.ts
Labels: release-no

#281 fix(package.json): fix search results page
  package.json
Labels: release-patch

#287 fix(locale-switcher): enable locale switcher for troubleshooting docs
  src/components/locale-switcher/index.tsx
  src/pages/troubleshooting/[slug].tsx
Labels: release-no

#288 chore(navigation.json): update navigation
  public/navigation.json
Labels: release-no, navigation

#283 feat: add ki alternative route
  src/pages/known-issues/[slug].tsx
  src/utils/resolveSlugFromKiFormat.ts
Labels: release-auto

#289 fix(known-issues): resolveSlugFromKiFormat returns the ki slug instea…
  src/pages/known-issues/[slug].tsx
  src/utils/resolveSlugFromKiFormat.ts
Labels: release-no

#291 feat(announcmenets): display contentful author
  src/components/author/index.tsx
  src/pages/announcements/[slug].tsx
  src/pages/docs/tracks/[slug].tsx
  src/pages/docs/tutorials/[slug].tsx
  src/pages/faq/[slug].tsx
  src/pages/known-issues/[slug].tsx
  src/pages/troubleshooting/[slug].tsx
  src/utils/constants.ts
  src/utils/fetchFileContributors.ts
  src/utils/fetchGithubUser.ts
Labels: release-patch

#293 fix(pages): various improvements
  public/navigation.json
  src/components/faq-section-card/styles.ts
  src/components/faq-section/styles.ts
  src/pages/announcements/[slug].tsx
  src/pages/docs/tracks/[slug].tsx
  src/pages/docs/tutorials/[slug].tsx
  src/pages/faq/[slug].tsx
  src/pages/index.tsx
  src/pages/known-issues/[slug].tsx
  src/pages/troubleshooting/[slug].tsx
  src/utils/getPagination.ts
Labels: release-no

#294 fix: replace contentful id with zendesk id in ki list
  src/pages/known-issues/index.tsx
Labels: release-auto

#297 chore(_app.ts): update meta-image
  src/pages/_app.tsx
Labels: release-no

#295 feat: add ki product team to ki page
  src/pages/known-issues/[slug].tsx
Labels: release-auto

#300 fix(faq): fix faq filters not being applied
  public/navigation.json
  src/components/tutorial-index/index.tsx
  src/pages/announcements/index.tsx
  src/pages/docs/tutorials/[slug].tsx
  src/pages/faq/index.tsx
  src/pages/known-issues/index.tsx
  src/styles/documentation-page.ts
Labels: release-no

#308 fix(troubleshooting): fix article index path
  src/pages/troubleshooting/[slug].tsx
Labels: release-no

#309 feat(article-index): add copy button and improve styles
  src/components/article-index/index.tsx
  src/styles/announcement-page.ts
  src/styles/documentation-page.ts
Labels: release-no
