Repository vtexdocs/helpcenter, pull requests merged in 2025-07, with the labels that each got.

#247 chore(url occurrences): change URL (newhelp.vtex.com)
  algolia/scraper_md.json
  navigation-optimization-strategy.md
  next.config.js
  src/pages/server-sitemap.xml/index.ts
  src/utils/getNavigation.ts
Labels: release-patch

#248 chore(navigation): update navigation.json file
  public/navigation.json
Labels: release-no

#251 chore(navigation): update navigation
  public/navigation.json
Labels: release-no

#253 feat: localize article pagination
  src/components/article-pagination/index.tsx
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
Labels: release-no

#245 feat: known issues integration
  src/pages/known-issues/[slug].tsx
  src/pages/known-issues/index.tsx
  src/utils/getDocsPaths.ts
Labels: release-auto

#256 fix(messages): support url
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
Labels: release-no
