Repository vtexdocs/helpcenter, pull requests merged in 2025-06, with the labels that each got.

#230 feat(apis): add github calls to api
  src/pages/api/ki-createupdate.ts
  src/pages/api/ki-gettree.ts
Labels: release-auto

#232 fix: modify troubleshooting items per page to 8
  src/pages/troubleshooting/index.tsx
Labels: release-auto

#233 fix: fix create/update api
  src/pages/api/ki-createupdate.ts
Labels: release-auto, priority-high

#234 feat(ki): delete known issue api
  src/pages/api/ki-delete.ts
Labels: release-auto

#231 Traffic tests announcement bar
  src/components/layout.tsx
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
Labels: release-minor

#237 feat(announcement bar href): add utm source
  src/components/layout.tsx
Labels: release-no

#235 refactor: migrate tracks/tutorials pages to getStaticProps/Paths, upd…
  .gitignore
  .trunk/.gitignore
  .trunk/configs/.markdownlint.yaml
  .trunk/configs/.shellcheckrc
  .trunk/configs/.yamllint.yaml
  .trunk/trunk.yaml
  BUNDLE_OPTIMIZATION.md
  Error
  analyze-bundle.js
  build.log
  navigation-fix-example.md
  navigation-optimization-strategy.md
  next.config.js
  package-lock.json
  package.json
  public/images/api-reference.png
  src/components/article-pagination/index.tsx
  src/components/breadcrumb/index.tsx
  src/components/header/index.tsx
  src/components/icons/api-reference-icon.tsx
  src/components/layout.tsx
  src/components/on-this-page/index.tsx
  src/components/table-of-contents-wrapper/index.tsx
  src/components/tutorial-index/index.tsx
  src/components/tutorial-markdown-render/index.tsx
  src/pages/_app.tsx
  src/pages/announcements/[slug].tsx
  src/pages/announcements/index.tsx
  src/pages/docs/tracks/[slug].tsx
  src/pages/docs/tutorials/[slug].tsx
  src/pages/faq/[slug].tsx
  src/pages/faq/index.tsx
  src/pages/index.tsx
  src/pages/known-issues/[slug].tsx
  src/pages/known-issues/index.tsx
  src/pages/search/index.tsx
  src/pages/troubleshooting/[slug].tsx
  src/pages/troubleshooting/index.tsx
  src/styles/global.css
  src/styles/rapidoc.css
  src/tests/cypress/integration/api-reference.cy.js
  src/types/navigation.ts
  src/utils/enumerate-navigation.ts
  src/utils/get-rapidoc.mjs
  src/utils/getDocsPaths.ts
  src/utils/getGithubFile.ts
  src/utils/getNavigation.ts
  src/utils/logging/log-util.ts
  src/utils/octokitConfig.ts
  src/utils/remark_plugins/plaiceholder.tsx
  src/utils/useClientNavigation.ts
  yarn.lock
Labels: release-minor

#238 fix(announcement bar message): remove the part about feedback
  src/messages/en.json
  src/messages/es.json
  src/messages/pt.json
Labels: release-no

#244 feat: implement performance optimizations based on Lighthouse audit
  src/components/layout.tsx
  src/components/newsletter-section/index.tsx
  src/components/page-header/index.tsx
  src/pages/404.tsx
  src/pages/500.tsx
  src/pages/announcements/index.tsx
  src/pages/docs/tracks/index.tsx
  src/pages/docs/tutorials/index.tsx
  src/pages/faq/index.tsx
  src/pages/index.tsx
  src/pages/known-issues/index.tsx
  src/pages/troubleshooting/index.tsx
  src/utils/contexts/trackerContext.tsx
Labels: release-minor
